#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG="$SCRIPT_DIR/config/runtime-pack.properties"
get_prop(){ awk -F= -v k="$1" '$1==k{print substr($0,index($0,"=")+1)}' "$CONFIG"; }
APP_ID="$(get_prop applicationId)"
UPSTREAM="$(get_prop nativeBuilderRepo)"
COMMIT="$(get_prop nativeBuilderCommit)"
ABI="$(get_prop nativeAbi)"
[ "$ABI" = "aarch64" ] || { echo "unsupported ABI: $ABI" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
SRC="$WORK/terminal-packages"
git clone --recurse-submodules "$UPSTREAM" "$SRC"
git -C "$SRC" checkout --detach "$COMMIT"
git -C "$SRC" submodule update --init --recursive
[ "$(git -C "$SRC" rev-parse HEAD)" = "$COMMIT" ] || { echo "upstream commit mismatch" >&2; exit 1; }

python3 - "$SRC/common.sh" "$SRC/packages.sh" <<'PY'
import pathlib, sys
common = pathlib.Path(sys.argv[1])
packages = pathlib.Path(sys.argv[2])
text = common.read_text(encoding="utf-8")
old = 'COTG_PACKAGE_NAME="com.itsaky.androidide"'
new = 'COTG_PACKAGE_NAME="com.jepongdevxyz.idebuild"'
if text.count(old) != 1:
    raise SystemExit("expected upstream applicationId assignment exactly once")
common.write_text(text.replace(old, new, 1), encoding="utf-8")

text = packages.read_text(encoding="utf-8")
needle = '    "openjdk-21"\n'
if text.count(needle) != 1:
    raise SystemExit("expected openjdk-21 base package exactly once")
if '    "aapt"\n' not in text:
    text = text.replace(needle, needle + '    "aapt"\n', 1)
packages.write_text(text, encoding="utf-8")
PY

grep -q 'COTG_PACKAGE_NAME="com.jepongdevxyz.idebuild"' "$SRC/common.sh"
grep -q '"aapt"' "$SRC/packages.sh"

# The pinned Termux ncurses dependency references Codeberg's generated foot
# 1.25.0 tag archive. Its generated bytes changed after the pinned Termux
# commit. Apply our fail-closed metadata override: it checks the exact old
# version, URL and SHA before replacing only the observed SHA-256.
python3 "$SCRIPT_DIR/upstream_source_overrides.py" \
  "$SRC/termux-packages/x11-packages/foot/build.sh"

# The pinned Termux properties file exports JAVA_HOME from TERMUX_JAVA_HOME.
# Preserve the JDK provisioned by GitHub Actions instead of letting upstream
# fall back to a distro-specific path that is absent on hosted runners.
: "${JAVA_HOME:?JAVA_HOME must be provided by the workflow}"
export TERMUX_JAVA_HOME="$JAVA_HOME"

# Use the pinned Termux toolchain bootstrap. It downloads the exact SDK/NDK
# revisions required by the pinned package source and verifies its pinned
# official Google SHA-256 values before the native package build starts.
"$SRC/termux-packages/scripts/setup-android-sdk.sh"

# Build only the Android-native capabilities DevxyzIDE needs. -e keeps the
# upstream builder from compiling its entire terminal package set; dependency
# closures for OpenJDK 21 and aapt are still built by termux build-package.
# This avoids unrelated terminal/UI sources becoming runtime-pack blockers.
(
  cd "$SRC"
  ./build.sh -a aarch64 -e openjdk-21 aapt
  ./generate-apt-repo.sh
)

# Generate a minimal bootstrap rooted at JDK21 and native aapt2. The local APT
# repository contains the dependency closure built above, and bootstrap
# generation resolves those dependencies into the archive.
# shellcheck disable=SC1090
. "$SRC/common.sh"
OUT_ARCH="$SRC/output/aarch64"
mkdir -p "$OUT_ARCH"
PACKAGES="openjdk-21,aapt2"
(
  cd "$OUT_ARCH"
  "$SRC/termux-packages/scripts/generate-bootstraps.sh" \
    --architectures aarch64 \
    --repository "file://$SRC/output/repo" \
    --add "$PACKAGES"
)

RAW="$OUT_ARCH/bootstrap-aarch64.zip"
[ -f "$RAW" ] || { echo "bootstrap output missing" >&2; exit 1; }
OUT="$SCRIPT_DIR/out/bootstrap/devxyz-bootstrap-aarch64.zip"
mkdir -p "$(dirname "$OUT")"
python3 "$REPO_ROOT/tools/runtime/stamp_bootstrap.py" \
  --input "$RAW" \
  --output "$OUT" \
  --application-id "$APP_ID" \
  --arch aarch64 \
  --upstream-commit "$COMMIT"
python3 "$SCRIPT_DIR/test_bootstrap_contract.py" "$OUT"
printf '%s\n' "$OUT"
