applicationId=com.jepongdevxyz.idebuild
nativeBuilderRepo=https://github.com/appdevforall/terminal-packages.git
nativeBuilderCommit=610af608b4a3b1127244e90edf8b7be2bf94fafa
nativeAbi=aarch64
gradleVersion=8.9
androidApi=35
